service: ts-service

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-central-1

functions:
  analysis:
    handler: functions/analyze.analysis
    events:
      - http:
          path: analyze
          method: post
  submitRequest:
    handler: functions/requests.submitRequest
    events:
      - http:
          path: requests
          method: post

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000