service: ts-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-central-1

functions:
  analysis:
    handler: functions/analyze.analysis
    events:
      - http:
          path: analyze
          method: post

plugins:
  - serverless-esbuild

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    target: node18
    platform: node
    exclude: []
    concurrency: 10
